name: me_calculator
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # Riverpod (안정 버전)
  flutter_riverpod: ^2.4.9

  # Functional programming
  dartz: ^0.10.1

  # Freezed annotation만 dependencies에
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 코드 생성 관련은 모두 dev_dependencies에
  build_runner: ^2.6.0
  freezed: ^3.2.0 # 여기로 이동
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - images/
